-- 报工事件流水表
-- 数据来源：ProduceReportLog.java + ProduceReportLogMapper.xml
-- 幂等，可重复执行

CREATE TABLE IF NOT EXISTS t_erp_produce_report_log (
    id                  BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键',
    job_id              BIGINT          DEFAULT NULL COMMENT '生产单ID',
    job_process_id      BIGINT          DEFAULT NULL COMMENT '工序快照ID',
    process_id          BIGINT          DEFAULT NULL COMMENT '工序定义ID',
    process_seq         INT             DEFAULT NULL COMMENT '工序序号',
    employee_id         BIGINT          DEFAULT NULL COMMENT '操作工ID',
    employee_name       VARCHAR(64)     DEFAULT NULL COMMENT '操作工姓名',
    operator_name       VARCHAR(64)     DEFAULT NULL COMMENT '扫描人姓名',
    team_name           VARCHAR(64)     DEFAULT NULL COMMENT '班组',
    machine_no          VARCHAR(64)     DEFAULT NULL COMMENT '机台号',
    report_qty          INT             DEFAULT NULL COMMENT '报工数量',
    completed_qty       INT             DEFAULT NULL COMMENT '合格数量',
    defect_qty          INT             DEFAULT NULL COMMENT '次品数量',
    loss_qty            INT             DEFAULT NULL COMMENT '损耗数量',
    report_type         VARCHAR(20)     DEFAULT NULL COMMENT '报工类型(SCAN/MANUAL/BATCH)',
    report_source       VARCHAR(20)     DEFAULT NULL COMMENT '报工来源(APP/WEB/PDA)',
    batch_no            VARCHAR(64)     DEFAULT NULL COMMENT '批次号',
    scan_token          VARCHAR(128)    DEFAULT NULL COMMENT '扫码令牌',
    billing_group_id    VARCHAR(64)     DEFAULT NULL COMMENT '计件组ID',
    is_outsourced       CHAR(1)         DEFAULT '0' COMMENT '是否外协(0否1是)',
    vendor_id           BIGINT          DEFAULT NULL COMMENT '外协供应商ID',
    validation_status   VARCHAR(20)     DEFAULT 'PENDING' COMMENT '校验状态(PENDING/PASS/REJECT)',
    validation_message  VARCHAR(500)    DEFAULT NULL COMMENT '校验信息',
    event_time          DATETIME        DEFAULT NULL COMMENT '事件发生时间',
    del_flag            CHAR(1)         DEFAULT '0' COMMENT '删除标记(0正常2删除)',
    create_by           VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time         DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by           VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time         DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark              VARCHAR(500)    DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (id),
    INDEX idx_rpt_job (job_id),
    INDEX idx_rpt_job_process (job_process_id),
    INDEX idx_rpt_process (process_id),
    INDEX idx_rpt_employee (employee_id),
    INDEX idx_rpt_event_time (event_time),
    INDEX idx_rpt_del_flag (del_flag),
    INDEX idx_rpt_validation (validation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报工事件流水表';
